### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by birdwell** [enricop89/multiparty-video-react-native#1]
Cloning this repo and running npm install fails. You might want to update the opentok package.
```
name@MacBook-Pro multiparty-video-react-native % npm i
npm ERR! code 1
npm ERR! Command failed: git checkout add-preferred-res-framerate
npm ERR! error: pathspec 'add-preferred-res-framerate' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2021-04-16T13_26_17_414Z-debug.log
```
After removing the git url and using the npm package instead, I get a nativeEvents.listeners is not a function.

**Comment by enricop89** [comment]
@birdwell thanks I updated the package.json. 
The `nativeEvents.listeners` is related to react-native 0.64 version. We are working on a release as we speak: https://github.com/opentok/opentok-react-native/pull/485
