### ISSUE TITLE
Destroy session

### ISSUE THREAD

**Issue by masmerino13** [enricop89/multiparty-video-react-native#5]
Hey guys, is there a method to destroy the session? like in the JS SDK, I'm using react navigation, and if User 1, end the call from the mobile, I can still hearing the other side (User 2).

I assume it's something related to React Navigation, but I want to see if there is a way to force the session to be destroyed.

thanks!

**Comment by enricop89** [comment]
Hi Ricardo, the only way to destroy the session is to destroy(unmount) the component. See an example with conditional rendering: https://github.com/enricop89/multiparty-video-react-native/blob/master/App.js#L371
